config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls', namespace='main'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import contacts, ProductListView, BlogListView, BlogDetailView,\
    BlogCreateView, BlogUpdateView, BlogDeleteView, ProductCreateView

from main.apps import MainConfig

app_name = MainConfig.name


urlpatterns = [
    path('', ProductListView.as_view(), name='product'),
    path('product/create', ProductCreateView.as_view(), name='product_create'),
    path('contacts/', contacts, name='contacts'),
    path('blog/', BlogListView.as_view(), name='blogs'),
    path('blog/<slug:slug>/', BlogDetailView.as_view(), name='blog_item'),
    path('blog/create/<slug:slug>', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<slug:slug>', BlogUpdateView.as_view(), name='blog_update_post'),
    path('blog/delete/<slug:slug>', BlogDeleteView.as_view(), name='blog_delete_post'),
]

main/models.py
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.utils.timezone import now
from django.db import models

from transliterate import translit
from transliterate import slugify as slu

DEFAULT = {
    'blank': True,
    'null': True,
}


class Product(models.Model):
    name = models.CharField(max_length=25, verbose_name='Название')
    description = models.CharField(max_length=25, verbose_name='Описание')
    image = models.ImageField(upload_to='image/')
    category = models.CharField(max_length=25, verbose_name='Категория')
    price = models.IntegerField(default=0, verbose_name='Цена')
    date_create = models.DateTimeField(default=now, verbose_name='Дата создания')
    date_of_change = models.DateTimeField

    def __str__(self):
        return f'{self.name}, {self.description}, {self.category}, {self.price}'

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ('name',)


class Category(models.Model):
    name = models.CharField(max_length=25, verbose_name='Название')
    description = models.CharField(max_length=25, verbose_name='Описание')

    def __str__(self):
        return self.name, self.description

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ('name',)


class Blogs(models.Model):
    """Модель `Блог`"""
    header = models.CharField(max_length=50, verbose_name='заголовок')
    slug = models.SlugField(verbose_name='slug', max_length=250, unique_for_date='create_data')
    content = models.TextField(max_length=250, verbose_name='содержимое')
    image = models.ImageField(**DEFAULT, upload_to='blog', verbose_name='превью')
    create_data = models.DateField(default=now, verbose_name='дата создания')
    sign = models.BooleanField(default=True, verbose_name='признак публикации')
    views = models.IntegerField(default=0, verbose_name='количество просмотров')

    is_active = models.BooleanField(default=True, verbose_name='Активный')

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()

    def add_view(self):
        self.views += 1
        self.save()
        return self.views

    def save(self, *args, **kwargs):
        if not self.slug:

            self.slug = slu(self.header)
        super(Blogs, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('main:blog_item', args=[self.slug])

    def __str__(self):
        return f'{self.header}, {self.content}, {self.image}, {self.create_data}'

    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"
        ordering = ('-pk',)

main/views.py
from django.views import generic
from main.productForm import ProductForm

from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy

from django.core.mail import send_mail

from main.models import Product, Blogs


class ProductListView(generic.ListView):
    model = Product


class ProductCreateView(generic.CreateView):
    model = Product
    form_class = ProductForm


def contacts(request):
    return render(request, 'main/contacts.html')


class BlogListView(generic.ListView):
    model = Blogs

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset.filter(is_active=True)
        queryset.filter(sign=False)
        return queryset


class BlogDetailView(generic.DetailView):
    model = Blogs

    def get_object(self, **kwargs):
        views = super().get_object()
        views.add_view()
        views.save()
        return views


class BlogCreateView(generic.CreateView):
    model = Blogs
    fields = ('header', 'content', 'sign', 'image')
    success_url = reverse_lazy('main:blogs')


class BlogUpdateView(generic.UpdateView):
    model = Blogs
    fields = ('header', 'content', 'sign', 'image')

    def get_success_url(self):  # Создаём функцию, которая даёт возможность пользователю остаться на странице с подробным отображением записи после завершения её редактирования.
        return reverse_lazy(
            "main:blog_item",
            kwargs={"slug": self.object.slug}
        )


class BlogDeleteView(generic.DeleteView):
    model = Blogs
    success_url = reverse_lazy('main:blogs')

main/templates/main/base.html
{% load static %}


<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Album example for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">


    <!-- Bootstrap core CSS -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
</head>

<body>
<header>
    {% include 'main/inckudes/inc_main_menu.html' %}

</header>

<main role="main">

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static "js/jquery-slim.min.js" %}"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

main/templates/main/blogs_confirm_delete.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="col-md-8 blog-main">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            Вы уверены, что хотите удалить запись "{{ object.header }}"?
            <input type="submit" class="btn btn-success" value="Уверен">
        </form>
    </div>
    <div class="card-footer">
        <a href="{% url 'main:blogs' %}" class="btn btn-primary"> Назад </a>
    </div>


</div><!-- /.blog-main -->

{% endblock %}

main/templates/main/blogs_detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
    <div class="col-md-8 blog-main">
        <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
                <strong class="d-inline-block mb-2 text-primary">World</strong>
                <h3 class="mb-0">
                    <a class="text-dark" href="#">{{ object.header }}</a>
                </h3>
                <div class="mb-1 text-muted">{{ object.create_data }}</div>
                <p class="card-text mb-auto">{{ object.content }}</p>
                <a> Просмотров: {{ object.views }}</a>
                <nav class="blog-pagination">
                    <a class="btn btn-warning" href={% url 'main:blog_update_post' object.slug %}>Изменить</a>
                    <a class="btn btn-danger" href={% url 'main:blog_delete_post' object.slug %}>Удалить</a>
                </nav>
            </div>


            {% if object.image %}
                <img class="card-img-right flex-auto d-none d-md-block" src="{{ object.image.url }}"
                     alt="Card image cap">

            {% endif %}
        </div>


    </div><!-- /.blog-main -->

{% endblock %}

main/templates/main/blogs_form.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="col-md-8 blog-main">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p  }}
            <input type="submit" class="btn btn-success" value="{% if object %}Сохранить{% else %}Добавить пост{% endif %}">
        </form>
    </div>


</div><!-- /.blog-main -->

{% endblock %}

main/templates/main/blogs_list.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}

    <div class="container">

        <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
            <div class="col-md-6 px-0">
                <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
            </div>
        </div>

        <div class="row mb-2">
            <div class="col-md-6">

            </div>
        </div>
    </div>

    <main role="main" class="container">
        <div class="row">
            <diov class="col-12">
                <a href="{% url 'main:blog_create' page_obj %}" class="btn btn-primary m-3 ">Написать пост</a>
            </diov>
            {% for object in object_list %}
                {% if object.is_active and object.sign %}
                <div class="col-md-8 blog-main">
                    <div class="card flex-md-row mb-4 box-shadow h-md-250">
                        <div class="card-body d-flex flex-column align-items-start">
                            <strong class="d-inline-block mb-2 text-primary">World</strong>
                            <h3 class="mb-0">
                                <a class="text-dark" href="#">{{ object.header }}</a>
                            </h3>
                            <div class="mb-1 text-muted">{{ object.create_data }}</div>
                            <p class="card-text mb-auto">{{ object.content }}</p>

                            <nav class="blog-pagination">
                                <a class="btn btn-outline-primary"
                                   href={{ object.slug }}>Смотреть</a>
                                <a> Просмотров: {{ object.views }}</a>
                            </nav>
                        </div>
                        {% if object.image %}
                            <img class="card-img-right flex-auto d-none d-md-block" src="{{ object.image.url }}"
                                 alt="Card image cap">
                        {% endif %}

                    </div>


                </div><!-- /.blog-main -->
                {% endif %}
            {% endfor %}

        </div><!-- /.row -->

    </main><!-- /.container -->
{% endblock %}

main/templates/main/contacts.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name"
                                   placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>

                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить
                    </button>
                </div>
            </div>
        </div>
    </div>


</div>

{% endblock %}

main/templates/main/inckudes/inc_main_menu.html
<div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
                <h4 class="text-white">About</h4>
                <p class="text-muted">Add some information about the album below, the author, or any other
                    background context. Make it a few sentences long so folks can pick up some informative tidbits.
                    Then, link them off to some social networking sites or contact information.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
                <h4 class="text-white">Меню</h4>
                <ul class="list-unstyled">
                    <li><a href="{% url 'main:product' %}" class="text-white">Главная</a></li>
                    <li><a href="{% url 'main:contacts' %}" class="text-white">Контакты</a></li>
                    <li><a href="{% url 'main:blogs' %}" class="text-white">Блог</a></li>
                    <li><a href="http://127.0.0.1:8000/admin/" class="text-white">Админка</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
        <a href="{% url 'main:product' %}" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                <circle cx="12" cy="13" r="4"></circle>
            </svg>
            <strong>Главная</strong>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>

main/templates/main/pages.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/static">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удобный сервис рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ 140</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Неограниченная лицензия</li>
                        <li>- Поддержка</li>
                        <li>- Установка на сервер</li>
                        <li>- Получение обновлений</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/js/bootstrap.bundle.min.js"></script>
</body>
</html>

main/templates/main/product_list.html
{% extends 'main/base.html' %}
{% load tag_filter %}
{% block content %}

{% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <img src="{{ object.image.url }}" alt="sa">
{#                <img src="{{ object.image.url|my_filter}}" alt="sa">#}
                <p class="card-text">{{ object }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endfor %}

{% endblock %}